---
version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    environment:
      - cluster.routing.allocation.disk.threshold_enabled=false
    ports:
      - 9200:9200
    networks: ['stack']

#  kibana:
#    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
#    links:
#      - elasticsearch
#    ports:
#      - 5601:5601
#    networks: ['stack']
#    depends_on:
#      - elasticsearch

networks:
  stack: {}
