= Demo project for Integration testing with Elasticsearch

This project shows how to run integration tests with elasticsearch.

== Step 5

This step assumes that you ran the previous branch https://github.com/dadoonet/elasticsearch-integration-tests/tree/04-check-if-already-running[04-check-if-already-running].

We want to able to run our tests against a https://cloud.elastic.co[cloud.elastic.co] instance.

Create your account on https://cloud.elastic.co[cloud.elastic.co] if you don't have one yet.
No credit card required for the 15 days trial!

Just start a new cluster either on AWS or GCP.
Get the `elastic` password you got at creation time and add the following properties in
your IDE for the test:

```
-Dtests.cluster.host=cloud_host_name
-Dtests.cluster.port=9243
-Dtests.cluster.scheme=https
-Dtests.cluster.user=elastic
-Dtests.cluster.pass=changeme
```

Then run the tests again. You will see that it does not start an instance and just connects
to the cloud.
If you created the Kibana instance as well when you created your elasticsearch cluster, you
can open it from the https://cloud.elastic.co[cloud console] and check from the developer console
that your data is there:

```
GET scenario1/_search
```

= License

```
This software is licensed under the Apache 2 license, quoted below.

Copyright 2018 Elastic

Licensed under the Apache License, Version 2.0 (the "License"); you may not
use this file except in compliance with the License. You may obtain a copy of
the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.
```
